import Head from 'next/head';
import {Menu, Header, Footer, Layout} from '../components';
import logo from '../public/assets/images/logo.png';
import * as axios from '../utills/axios';
import { useEffect, useState } from 'react';
import {dispatch, useStoreState} from "@/store/account";
import {setCookie, getCookie, hasCookie, deleteCookie} from 'cookies-next';
import moment from "moment";
import {useNotify} from "@/utills/useNotify";
import {faCheck, faCheckCircle, faGear, faLock, faUserCircle} from "@fortawesome/free-solid-svg-icons";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";

export default function Home({Component, pageProps}) {
    const info = useStoreState('info');
    const user = useStoreState('detail');

    async function getInfo() {
        await axios.callApi('GET', 'admin/v1/info').then(res => {
            let { code, data, message } = res
            if(code === 0) {
                dispatch({type: 'SET_USER_INFO', data: data})
            }
        }).catch(e => {
            useNotify('error', e.message)
        })
    }

    useEffect(() => {
        console.log(12212)
        getInfo()
    }, []);

    return (
        <>
            <Head>
                <title>EZB68</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <>
                <div className="container">
                    <div className="row mx-0 mb-4">
                        <div className="col-lg-4 px-0">
                            <div className="profile-block h-100 p-3">
                                <div className="d-flex justify-content-between pb-2 border-bottom border-color mb-3">
                                    <div className="tag-item">
                                        <div className="icon me-2 text-highline"><FontAwesomeIcon className="" icon={faUserCircle}/></div>{info.userName}
                                    </div>
                                    <div className="btn btn-setting"><FontAwesomeIcon className="" icon={faGear}/></div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Nickname :</div>
                                    <div className="col-8">{info.userName}</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Account Type :</div>
                                    <div className="col-8">Master Agent</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Currency :</div>
                                    <div className="col-8">USD, VND</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Status :</div>
                                    <div className="col-8"><span className="me-3">{info.status}</span>
                                        {
                                            info.status === 'ACTIVE' ? (
                                                <FontAwesomeIcon className="" icon={faCheckCircle}/>
                                            ) : (
                                                <FontAwesomeIcon className="" icon={faLock}/>
                                            )
                                        }
                                    </div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Phone :</div>
                                    <div className="col-8">{info.phone}</div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-4 px-0">
                            <div className="profile-block p-3 h-100">
                                <div className="text-light mb-3">Created Time : {info.createdDate}</div>
                                <div className="text-light">Last Login : {info.lastLogin}</div>
                            </div>
                        </div>
                        <div className="col-lg-4 px-0">
                            <div className="profile-block h-100 p-3">
                                <div className="text-light mb-3">Total Agents</div>
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex align-items-center">
                                        <div className="icon bg-success me-2">
                                            <FontAwesomeIcon className="" icon={faCheck}/>
                                        </div>{info.totalAgentActive}
                                    </div>
                                    {/*<div className="d-flex align-items-center">*/}
                                    {/*    <div className="icon me-2"><i className="fas fa-link"></i></div>000*/}
                                    {/*</div>*/}
                                    <div className="d-flex align-items-center">
                                        <div className="icon me-2 bg-danger">
                                            <FontAwesomeIcon className="" icon={faLock}/>
                                        </div>{info.totalAgentLock}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="row mx-0 py-3 mb-3 border-bottom border-color">
                        <div className="col-8 col-lg-4">My PT AllowedCommission</div>
                        <div className="col-4 col-lg-8">Commission</div>
                    </div>
                    <div className="row mx-0 pb-3">
                        <div className="col-6 col-lg-4"><span className="me-4">SEXYBCRT_LIVE:</span>0.00%</div>
                        <div className="col-6 col-lg-8"><span className="me-4">SEXYBCRT_LIVE:</span>0.00%</div>
                    </div>
                </div>
            </>
        </>
    )
}
