import Head from 'next/head';
import {TagLink, Header, Footer, Layout} from '../components';
import logo from '../public/assets/images/logo.png';
import * as axios from '../helpers/axios';
import { useEffect, useState } from 'react';

export default function Home({Component, pageProps}) {
    const [info, setInfo] = useState({});

    async function getInfo() {
        await axios.callApi('GET', '/api/auth/v1/info', {})
        .then(res => {
            setInfo(res.data)
        })
    };

    useEffect(() => {
        // getInfo();
        setInfo({
            userName: "username",
            phone: '0213431656',
            createdDate: '2023-05-18T08:46:32.988Z',
            lastLogin: "2023-05-18T08:46:32.988Z",
            status: "LOCK",
            totalAgentActive: 0,
            totalAgentLock: 0
        })
    }, []);

    return (
        <>
            <Head>
                <title>EZB68</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                {/*<Script src="@/assets/js/all.min.js"></Script>*/}
                {/*<Script src="../assets/js/bootstrap.bundle.min.js"></Script>*/}
                {/*<Script src="@/assets/js/jquery.min.js"></Script>*/}
                {/*<Script src="@/assets/slick/slick.min.js"></Script>*/}
                {/*<Script src="@/assets/js/wow/wow.min.js"></Script>*/}
                {/*<Script src="@/assets/js/moment.min.js"></Script>*/}
                {/*<Script src="@/assets/js/daterangepicker.min.js"></Script>*/}
                {/*<Script src="../assets/js/apexcharts.min.js"></Script>*/}
                {/*<Script src="../assets/js/chart-custom.min.js"></Script>ßßß*/}
                {/*<Script src="@/assets/js/menu-toggle.min.js"></Script>*/}
                {/*<Script src="@/assets/js/main.js"></Script>*/}
            </Head>
            <>
                <div className="container">
                    <div className="row mx-0 mb-4">
                        <div className="col-lg-4 px-0">
                            <div className="profile-block h-100 p-3">
                                <div className="d-flex justify-content-between pb-2 border-bottom border-color mb-3">
                                    <div className="tag-item">
                                        <div className="icon me-2 text-highline"><i className="fas fa-user-circle"></i></div>{info.userName}
                                    </div>
                                    <div className="btn btn-setting"><i className="fa-solid fa-gear"></i></div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Nickname :</div>
                                    <div className="col-8">AA-SonicXGame</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Account Type :</div>
                                    <div className="col-8">Master Agent</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Currency :</div>
                                    <div className="col-8">USD, VND</div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Status :</div>
                                    <div className="col-8"><span className="me-3">{info.status}</span><i className={info.status === 'ACTIVE' ? "fas fa-check-circle text-success" : "fas fa-lock"} ></i></div>
                                </div>
                                <div className="row mb-3">
                                    <div className="col-4">Phone :</div>
                                    <div className="col-8">{info.phone}</div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-4 px-0">
                            <div className="profile-block p-3 h-100">
                                <div className="text-light mb-3">Created Time : {info.createdDate}</div>
                                <div className="text-light">Last Login : {info.lastLogin}</div>
                            </div>
                        </div>
                        <div className="col-lg-4 px-0">
                            <div className="profile-block h-100 p-3">
                                <div className="text-light mb-3">Total Agents</div>
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex align-items-center">
                                        <div className="icon bg-success me-2"><i className="fas fa-check"></i></div>{info.totalAgentActive}
                                    </div>
                                    <div className="d-flex align-items-center">
                                        <div className="icon me-2"><i className="fas fa-link"></i></div>000
                                    </div>
                                    <div className="d-flex align-items-center">
                                        <div className="icon me-2 bg-danger"><i className="fas fa-lock"></i></div>{info.totalAgentLock}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="row mx-0 py-3 mb-3 border-bottom border-color">
                        <div className="col-8 col-lg-4">My PT AllowedCommission</div>
                        <div className="col-4 col-lg-8">Commission</div>
                    </div>
                    <div className="row mx-0 pb-3">
                        <div className="col-6 col-lg-4"><span className="me-4">SEXYBCRT_LIVE:</span>0.00%</div>
                        <div className="col-6 col-lg-8"><span className="me-4">SEXYBCRT_LIVE:</span>0.00%</div>
                    </div>
                </div>
            </>
        </>
    )
}
